// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: grpc/interface.proto

package handin_04

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EnterClient is the client API for Enter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EnterClient interface {
	Enter(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
}

type enterClient struct {
	cc grpc.ClientConnInterface
}

func NewEnterClient(cc grpc.ClientConnInterface) EnterClient {
	return &enterClient{cc}
}

func (c *enterClient) Enter(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/handin_04.enter/enter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnterServer is the server API for Enter service.
// All implementations must embed UnimplementedEnterServer
// for forward compatibility
type EnterServer interface {
	Enter(context.Context, *Request) (*Reply, error)
	mustEmbedUnimplementedEnterServer()
}

// UnimplementedEnterServer must be embedded to have forward compatible implementations.
type UnimplementedEnterServer struct {
}

func (UnimplementedEnterServer) Enter(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Enter not implemented")
}
func (UnimplementedEnterServer) mustEmbedUnimplementedEnterServer() {}

// UnsafeEnterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnterServer will
// result in compilation errors.
type UnsafeEnterServer interface {
	mustEmbedUnimplementedEnterServer()
}

func RegisterEnterServer(s grpc.ServiceRegistrar, srv EnterServer) {
	s.RegisterService(&Enter_ServiceDesc, srv)
}

func _Enter_Enter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnterServer).Enter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/handin_04.enter/enter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnterServer).Enter(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Enter_ServiceDesc is the grpc.ServiceDesc for Enter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Enter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "handin_04.enter",
	HandlerType: (*EnterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "enter",
			Handler:    _Enter_Enter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/interface.proto",
}
